name: CI

on:
  push:
    branches-ignore:
      - master
  schedule:
    - cron: '50 6 * * 3'

env:
  GRAALVM_VERSION: 21.0.0

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        env:
          REVISION: ${{ github.sha }}
        run: |
          wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${{ env.GRAALVM_VERSION }}/graalvm-ce-java11-darwin-amd64-${{ env.GRAALVM_VERSION }}.tar.gz
          tar xzf graalvm-ce-java11-darwin-amd64-${{ env.GRAALVM_VERSION }}.tar.gz
          export JAVA_HOME="$(pwd)/graalvm-ce-java11-${{ env.GRAALVM_VERSION }}/Contents/Home/"
          ${JAVA_HOME}/bin/gu install native-image
          brew install upx
          ./mvnw \
            --batch-mode \
            -Dsha1="${GITHUB_SHA}" \
            -Drevision="${REVISION}" \
            verify
          "./target/drupal-cli-macos-${REVISION}"
          upx --brute "target/drupal-cli-macos-${REVISION}"
          "./target/drupal-cli-macos-${REVISION}"
          mkdir target/artifacts
          cp target/drupal-cli-* target/artifacts
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: drupal-cli-${{ github.job }}-${{ github.sha }}
          path: target/artifacts
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        env:
          REVISION: ${{ github.sha }}
        run: |
          wget -q https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar xf upx-3.96-amd64_linux.tar.xz
          wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${{ env.GRAALVM_VERSION }}/graalvm-ce-java11-linux-amd64-${{ env.GRAALVM_VERSION }}.tar.gz
          tar xzf graalvm-ce-java11-linux-amd64-${{ env.GRAALVM_VERSION }}.tar.gz
          export JAVA_HOME="$(pwd)/graalvm-ce-java11-${{ env.GRAALVM_VERSION }}"
          ${JAVA_HOME}/bin/gu install native-image
          ./mvnw \
            --batch-mode \
            -Dsha1="${GITHUB_SHA}" \
            -Drevision="${REVISION}" \
            verify
          "./target/drupal-cli-linux-${REVISION}"
          ./upx-3.96-amd64_linux/upx --brute "target/drupal-cli-linux-${REVISION}"
          "./target/drupal-cli-linux-${REVISION}"
          mkdir target/artifacts
          cp target/drupal-cli-* target/artifacts
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: drupal-cli-${{ github.job }}-${{ github.sha }}
          path: target/artifacts
  windows:
    runs-on: windows-latest
    env:
      VCVARS_BAT: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: choco install graalvm --version=${{ env.GRAALVM_VERSION }} --no-progress
      - run: choco install upx --version=3.96 --no-progress
      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: .m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        shell: cmd
        env:
          JAVA_HOME: C:\Program Files\GraalVM\graalvm-ce-java11-${{ env.GRAALVM_VERSION }}
          REVISION: ${{ github.sha }}
        run: |
          call "%JAVA_HOME%\bin\gu" install native-image
          call "%VCVARS_BAT%"
          call .\mvnw --batch-mode -Dsha1="%GITHUB_SHA%" -Drevision="%REVISION%" --settings .\.github\github-actions-windows-maven-settings.xml  verify
          .\target\drupal-cli-windows-%REVISION%.exe
          upx --brute target/drupal-cli-windows-%REVISION%.exe
          .\target\drupal-cli-windows-%REVISION%.exe
          mkdir target\artifacts
          copy target\drupal-cli-* target\artifacts
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: drupal-cli-${{ github.job }}-${{ github.sha }}
          path: target/artifacts
  deploy:
    needs: [macos, linux, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVISION: ${{ github.sha }}
        run: |
          ./mvnw \
            --batch-mode \
            --settings ./.github/github-packages-maven-settings.xml \
            -Dsha1="${GITHUB_SHA}" \
            -Drevision="${REVISION}" \
            -DaltDeploymentRepository="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}" \
            deploy
